name: emori
description: Emori mobile app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flutter_cupertino_date_picker: ^1.0.26+2
  logging: ^1.0.2
  intl: ^0.17.0
  flutter_native_splash: ^1.3.2
  flutter_svg: ^1.0.3
  drag_select_grid_view: ^0.5.1
  dotted_border: ^2.0.0+2
  scribble: ^0.2.1
  flutter_state_notifier: ^0.7.1
  flutter_painter: ^1.0.1
  flutter_phosphor_icons: ^0.0.1+6
  flutter_screenutil: ^5.5.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Add assets to your application like this:
  assets:
  - assets/images/auth_backgrounds/
  - assets/images/intro_backgrounds/first_intro/
  - assets/images/intro_backgrounds/second_intro/
  - assets/images/intro_backgrounds/third_intro/
  - assets/images/intro_backgrounds/fourth_intro/
  - assets/images/intro_backgrounds/fifth_intro/
  - assets/images/questionnaire_backgrounds/
  - assets/images/common/
  - assets/images/main_menu_tiles/
  - assets/images/interactive_task_backgrounds/draw_task/
  - assets/images/interactive_task_backgrounds/draw_task_intro/
  fonts:
    - family: Readex Pro
      fonts:
        - asset: assets/fonts/body/ReadexPro-Regular.ttf
    - family: Montagu Slab
      fonts:
        - asset: assets/fonts/header/MontaguSlab-700-bold.ttf

#Run commands to generate splash screen
# 1) flutter clean
# 2) flutter pub get
# 3) flutter pub run flutter_native_splash:create
flutter_native_splash:
    background_image: "assets/images/splash_screen.png"